# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M8mb4u9JhPTKvvjV6J_54fiVjVfFI0KB
"""

a = int(input("Введи делимое:"))
b = int(input("Введи делитель:"))
try:
 x = a//b
 print ("Результат", x)
except ZeroDivisionError:
 print ("Деление на 0")
finally:
  print ("Отработал блок файнали")
  a = int(input("Введи делимое:"))
  b = int(input("Введи делитель:"))
  x = a//b
  print ("Результат", x)

import random
x = ['kuzn','killer','danil','smit','odegov','karry']
print (random.choice(x))